FROM node:22-alpine

WORKDIR /app

ENV CI=true

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY frontend/package.json ./frontend/package.json

RUN corepack enable && corepack install
RUN pnpm install --frozen-lockfile --filter frontend...

COPY frontend ./frontend

WORKDIR /app/frontend

# Expose port
EXPOSE 3000

# Start dev server
CMD ["node", "node_modules/next/dist/bin/next", "dev", "--webpack", "-H", "0.0.0.0"]
