import { test, expect } from '@playwright/test';
import { installAdminMocks, buildAdminApiEnvelope } from './helpers/admin-operator-fixture';
import { observeAdminBrowserEvidence, writeAdminVisualReceipt } from './helpers/admin-visual-receipt';

test.use({ timezoneId: 'Asia/Shanghai' });

test('usage counts, period filters and source failure stay honest', async ({ page }, testInfo) => {
  const evidence = observeAdminBrowserEvidence(page);
  await page.setViewportSize({ width: 1440, height: 1050 });
  await installAdminMocks(page);
  let pluginFail = false;
  let runtimeFail = false;
  let truncated = false;
  const requests: string[] = [];
  const row = { id: 'site-a', runs: 12, failed: 2, success_rate: 0.75, avg_latency_ms: 1200 };
  await page.route('**/api/admin/runtime-telemetry*', route => {
    requests.push(route.request().url());
    if (runtimeFail) return route.fulfill({ status: 503, json: {} });
    return route.fulfill({ json: buildAdminApiEnvelope({ generated_at: '2026-09-10T12:00:00Z', window: { since: '2026-09-03T12:00:00Z', until: '2026-09-10T12:00:00Z' }, usage_statistics: { ...row, active_sites: 1, latency_samples: 10, possibly_truncated: truncated, sites: [row], functions: [{ ...row, id: 'wp-ai.classification' }], timeline: [{ ...row, day: '2026-09-10' }], comparison: { sites: { series: [{ id: 'site-a', points: [{ day: '2026-09-10', runs: 12, failed: 2 }] }], other: [], group_count: 1 }, functions: { series: [{ id: 'wp-ai.classification', points: [{ day: '2026-09-10', runs: 12, failed: 2 }] }], other: [], group_count: 1 } } } }) });
  });
  await page.route('**/api/admin/plugin-observability*', route => route.fulfill(pluginFail ? { status: 503, json: {} } : { json: buildAdminApiEnvelope({ generated_at: '2026-09-10T12:00:00Z', totals: { events_total: 23, active_site_count: 1 }, plugins: [{ plugin_slug: 'test-plugin', events_total: 23, error_total: 1, success_rate: 22 / 23, avg_latency_ms: 200 }], recent_activity: [
    { event_id: 'event-1', plugin_slug: 'npcink-cloud-addon', site_id: 'site-a', status: 'ok', received_at: '2026-09-10T12:00:00Z', event_kind: route.request().url().includes('record_scope=test') ? 'validation.technical_monitoring_only' : 'addon.monitoring.state_projected' },
    { event_id: 'event-2', plugin_slug: 'npcink-cloud-addon', site_id: 'site-a', status: 'ok', received_at: '2026-09-10T11:00:00Z', event_kind: route.request().url().includes('record_scope=test') ? 'validation.technical_monitoring_only' : 'addon.monitoring.state_projected' },
  ], timeline: [{ bucket_start_at: '2026-09-10T12:00:00Z', events_total: 23, error_total: 1 }] }) }));
  await page.route('**/api/admin/plugin-observability/history?*', route => route.fulfill(pluginFail ? { status: 503, json: {} } : { json: buildAdminApiEnvelope({ items: [{ site_id: 'site-a', plugin_slug: 'npcink-cloud-addon', event_kind: route.request().url().includes('record_scope=test') ? 'validation.technical_monitoring_only' : 'addon.monitoring.state_projected', received_at: '2026-09-10T12:00:00Z', events: 2, failed: 0 }], page: 1, pages: 1, total: 1, totals: { events: 2, failed: 0, succeeded: 2 }, snapshot: { at: '2026-09-10T12:00:00Z', id: 2 } }) }));
  await page.goto('/admin/usage-statistics');
  const toolbar = page.locator('[data-ui="usage-statistics-toolbar"]');
  await expect(toolbar).toBeVisible();
  const toolbarBox = await toolbar.boundingBox();
  expect(toolbarBox).not.toBeNull();
  expect(await toolbar.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await expect(page.locator('[data-ui="backoffice-page-header"]')).toContainText('12');
  const definitions = page.locator('[data-ui="usage-definitions"]');
  await expect(definitions).not.toHaveAttribute('open', '');
  await expect(definitions.locator('dl')).toBeHidden();
  const collapsedDefinitions = (await definitions.boundingBox())!;
  const metricHints = page.locator('[data-ui="backoffice-page-header"] [data-density="compact"] .backoffice-info-hint');
  await expect(metricHints).toHaveCount(4);
  const rateHint = metricHints.filter({ hasText: 'i' }).nth(2);
  await expect(rateHint).toHaveAttribute('aria-label', /运行成功率|Run success rate/);
  await expect(rateHint.locator('..')).not.toHaveAttribute('title');
  await rateHint.focus();
  await expect(page.getByRole('tooltip')).toContainText(/处理中任务计入分母|processing tasks remain in the denominator/);
  await page.screenshot({ path: testInfo.outputPath('metric-definition-1440.png'), fullPage: true });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('tooltip')).toBeHidden();
  await metricHints.nth(3).hover();
  await expect(page.getByRole('tooltip')).toContainText(/开始和结束时间|start and finish times/);
  await definitions.locator('summary').click();
  await expect(definitions.locator('dd')).toHaveCount(3);
  await expect(definitions.locator('dl')).toBeVisible();
  await expect(definitions).not.toContainText(/插件记录|Plugin records/);
  expect((await definitions.boundingBox())!.height).toBeGreaterThan(collapsedDefinitions.height);
  await page.screenshot({ path: testInfo.outputPath('definitions-expanded-1440.png'), fullPage: true });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.screenshot({ path: testInfo.outputPath('definitions-expanded-1920.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await definitions.locator('summary').click();
  await expect(definitions.locator('dl')).toBeHidden();
  const viewTabs = toolbar.getByRole('tablist', { name: /Runtime analysis view|运行分析视图/ });
  await expect(viewTabs).toBeVisible();
  await expect(viewTabs.getByRole('tab', { name: /Table|表格/ })).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('group', { name: /Statistics dimension|统计维度/ })).toBeVisible();
  await expect(page.locator('[data-ui="usage-more-reference"]')).toBeHidden();
  const tabsBox = (await viewTabs.boundingBox())!;
  const refreshBox = (await toolbar.getByRole('button', { name: /^Refresh$|^刷新$/ }).boundingBox())!;
  expect(Math.abs(tabsBox.y - refreshBox.y)).toBeLessThan(2);
  expect(tabsBox.x).toBeGreaterThan(refreshBox.x + refreshBox.width);
  const dimensionBox = (await page.getByRole('group', { name: /Statistics dimension|统计维度/ }).boundingBox())!;
  const tableBox = (await page.locator('[data-ui="usage-breakdown"]').boundingBox())!;
  expect(tableBox.y - dimensionBox.y - dimensionBox.height).toBeLessThan(24);
  await page.screenshot({ path: testInfo.outputPath('table-ready.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(viewTabs).toBeVisible();
  expect(await toolbar.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('table-narrow.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await expect(page.getByRole('link', { name: /Site diagnostics|站点诊断/ })).toHaveAttribute('href', '/admin/troubleshooting?window=336&from=usage-statistics&site=site-a');
  await page.getByRole('link', { name: /By function|按功能/ }).click();
  await expect(page.locator('[data-ui="usage-breakdown"]')).toContainText(/Classification|内容分类/);
  await expect(page.getByRole('link', { name: /Function diagnostics|功能诊断/ })).toHaveAttribute('href', '/admin/troubleshooting?window=336&from=usage-statistics&function=wp-ai.classification');
  await page.getByRole('link', { name: /Plugin activity records|插件运行记录/ }).click();
  await page.getByRole('tab', { name: /Table|表格/ }).click();
  const events = page.locator('[data-ui="usage-recent-activity"]');
  await expect(events.getByRole('heading', { name: /Plugin events|插件事件/, exact: true })).toBeVisible();
  await expect(events.locator('tbody tr')).toHaveCount(1);
  await expect(events.locator('tbody')).toContainText('2');
  await expect(page.getByRole('heading', { name: /Recent reports|近期上报记录|插件上报事件/ })).toHaveCount(0);
  await expect(page.getByText(/未关联运行表示暂无对应运行证据/)).toBeHidden();
  await expect(page.getByRole('link', { name: /View technical validation records|查看技术验证记录/, includeHidden: true })).toBeHidden();
  await expect(page.locator('[data-ui="usage-breakdown"]')).toBeHidden();
  const pluginDimensionBox = (await page.getByRole('group', { name: /Statistics dimension|统计维度/ }).boundingBox())!;
  const eventsBox = (await events.boundingBox())!;
  expect(eventsBox.y - pluginDimensionBox.y - pluginDimensionBox.height).toBeLessThan(24);
  await page.screenshot({ path: testInfo.outputPath('plugin-clean-1440.png'), fullPage: true });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.screenshot({ path: testInfo.outputPath('plugin-clean-1920.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await expect(page.locator('[data-ui="backoffice-page-header"]')).toContainText('Asia/Shanghai');
  await expect(page.locator('[data-ui="backoffice-page-header"]')).toContainText('20:00');
  await page.getByRole('tab', { name: /Chart|图表/ }).click();
  await expect(page.getByRole('group', { name: /Statistics dimension|统计维度/ })).toBeVisible();
  await expect(page.locator('[data-ui="usage-recent-activity"]')).toBeHidden();
  await expect(page.getByRole('heading', { name: /Site comparison|按站点对比/ })).toBeVisible();
  await expect(page.locator('[data-ui="backoffice-page-header"]')).not.toContainText('插件记录');
  await page.screenshot({ path: testInfo.outputPath('chart-ready.png'), fullPage: true });
  const observationTabs = page.locator('[data-ui="admin-observability-tabs"]');
  await expect(observationTabs.getByRole('link')).toHaveCount(4);
  await expect(observationTabs.locator('[aria-current="page"]')).toHaveCount(1);
  await expect(observationTabs.getByRole('link', { name: /Media observability|媒体观测/ })).toHaveAttribute('href', '/admin/media-observability?window=336');
  await expect(observationTabs.getByRole('link', { name: /Vector observability|向量观测/ })).toHaveAttribute('href', '/admin/vector-observability?window=336');
  await expect(page.locator('[data-ui="usage-related-observability"]')).toHaveCount(0);
  await page.getByRole('tab', { name: /Table|表格/ }).click();
  await page.getByRole('link', { name: /Plugin activity records|插件运行记录/ }).click();
  await page.screenshot({ path: testInfo.outputPath('plugin-table.png'), fullPage: true });
  await definitions.locator('summary').click();
  await expect(definitions).toContainText(/does not create or run tests|不会创建或执行测试/);
  await expect(definitions).toContainText(/同一快照|one snapshot/);
  await expect(definitions).not.toContainText(/处理中任务计入分母|processing tasks remain in the denominator/);
  await page.screenshot({ path: testInfo.outputPath('plugin-definitions-expanded.png'), fullPage: true });
  const testRequest = page.waitForRequest(request => request.url().includes('record_scope=test'));
  await definitions.getByRole('link', { name: /View technical validation records|查看技术验证记录/ }).click();
  await testRequest;
  await expect(page).toHaveURL(/records=test/);
  await expect(page.locator('[data-ui="usage-test-scope"]')).toContainText(/Technical validation records|技术验证记录/);
  await expect(events.locator('code')).toHaveText('validation.technical_monitoring_only');
  await page.reload();
  await expect(page.locator('[data-ui="usage-test-scope"]')).toBeVisible();
  await expect(definitions).not.toHaveAttribute('open', '');
  await page.screenshot({ path: testInfo.outputPath('plugin-test-scope.png'), fullPage: true });
  const operationalRequest = page.waitForRequest(request => request.url().includes('record_scope=operational'));
  await page.getByRole('link', { name: /Back to activity records|返回运行记录/ }).click();
  await operationalRequest;
  await expect(page.locator('[data-ui="usage-test-scope"]')).toHaveCount(0);
  await page.getByRole('button', { name: /^14 days$|^14 天$/ }).click();
  await expect.poll(() => requests.some(url => url.includes('recent_minutes=20160'))).toBe(true);
  await expect(page).toHaveURL(/window=336/);
  await page.reload();
  await expect(page.getByRole('button', { name: /^14 days$|^14 天$/ })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('group', { name: /Statistics dimension|统计维度/ })).toBeVisible();
  await expect(viewTabs.getByRole('tab', { name: /Table|表格/ })).toHaveAttribute('aria-selected', 'true');
  await page.getByRole('link', { name: /Plugin activity records|插件运行记录/ }).click();
  await expect(page.locator('[data-ui="usage-recent-activity"]')).toBeVisible();
  await page.goBack();
  await expect(page).not.toHaveURL(/window=336/);
  await page.goForward();
  await expect(page).toHaveURL(/window=336/);
  await expect(page.getByRole('button', { name: /^Refresh$|^刷新$/ })).toBeEnabled();
  pluginFail = true;
  await page.getByRole('button', { name: /^Refresh$|^刷新$/ }).click();
  await expect(page.locator('p[role="alert"]')).toBeVisible();
  await expect(page.locator('[data-ui="backoffice-page-header"]')).toContainText('12');
  await expect(events.locator('tbody tr')).toHaveCount(0);
  await expect(events).not.toContainText('2 条记录');
  await expect(events).toContainText(/History could not be loaded|记录加载失败/);
  pluginFail = false;
  runtimeFail = true;
  await page.getByRole('tab', { name: /Chart|图表/ }).click();
  await page.getByRole('button', { name: /^Refresh$|^刷新$/ }).click();
  await expect(page.locator('[data-ui="usage-more-reference"]').getByText(/Runtime statistics unavailable|运行统计暂不可用/, { exact: true })).toBeVisible();
  await expect(page.locator('[data-ui="usage-recent-activity"]')).toBeHidden();
  await expect(page.locator('[data-ui="backoffice-page-header"]')).toContainText(/Unknown|未知/);
  runtimeFail = false;
  truncated = true;
  await page.getByRole('button', { name: /^Refresh$|^刷新$/ }).click();
  await expect(page.getByText(/5,000-run cap reached|已达到 5000 条上限/)).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('chart-truncated.png'), fullPage: true });
  await writeAdminVisualReceipt({ page, testInfo, dataMode: 'mocked', route: '/admin/usage-statistics', pageModel: 'diagnostic', testedStates: ['ready', 'filtered', 'partial_error'], pageTitle: page.getByRole('heading', { name: /Usage Statistics|使用统计/, exact: true }), workingSurface: page.locator('[data-ui="usage-statistics-workspace"]'), browserEvidence: evidence, humanAcceptance: 'pending', expectedConsoleErrors: [/503/], routeRuleResults: [
    { id: 'single-primary-action', status: 'not_applicable', evidence: 'read-only filters and navigation' },
    { id: 'textual-status', status: 'pass', evidence: 'explicit source error and unavailable text' },
    { id: 'action-object-proximity', status: 'pass', evidence: 'site and function diagnostic links preserve identity; test scope returns to activity records' },
    { id: 'distinct-interaction-states', status: 'pass', evidence: 'aria-current window and dimension links' },
    { id: 'dialog-focus-recovery', status: 'not_applicable', evidence: 'no dialog' },
    { id: 'context-stability', status: 'pass', evidence: 'URL retains scope; independent source remains available' },
  ], interactionResults: [{ id: 'filters-and-partial-failure', status: 'pass', evidence: 'period requests, dimension links, and partial source failures verified' }] });
});
