import { expect, test, type Page, type Route } from '@playwright/test';

const BASE_URL =
  process.env.MAGICK_AI_CLOUD_FRONTEND_BASE_URL ||
  `http://127.0.0.1:${process.env.MAGICK_AI_CLOUD_FRONTEND_PORT || '3301'}`;

test.skip(
  !process.env.MAGICK_AI_CLOUD_FRONTEND_BASE_URL,
  'agent/workflow metadata smoke expects a running Cloud dev surface'
);

async function expectNoConsoleFailures(page: Page) {
  const messages: string[] = [];
  page.on('console', (message) => {
    if (message.type() === 'error') {
      const text = message.text();
      if (!text.includes('favicon.ico') && !text.startsWith('Failed to load resource:')) {
        messages.push(text);
      }
    }
  });
  page.on('pageerror', (error) => messages.push(error.message));
  return () => expect(messages).toEqual([]);
}

async function fulfillJson(route: Route, data: unknown) {
  await route.fulfill({
    status: 200,
    contentType: 'application/json',
    body: JSON.stringify({ status: 'ok', data, meta: { revision: 'smoke' } }),
  });
}

async function installPortalAIInsightMocks(page: Page) {
  await page.context().addCookies([
    {
      name: 'magick_portal_session_token',
      value: 'e2e-portal-session',
      url: BASE_URL,
    },
  ]);

  await page.route(/\/(?:api\/portal|portal\/v1)\/.*/, async (route) => {
    const url = new URL(route.request().url());
    const pathname = url.pathname.replace(/^\/api\/portal/, '').replace(/^\/portal\/v1/, '');

    if (pathname === '/session') {
      await fulfillJson(route, {
        member_ref: 'user:portal-agent-smoke@example.com',
        site_id: 'site_agent_smoke',
        account_id: 'acct_agent_smoke',
        identity_type: 'user',
        role: 'user',
        allowed_actions: ['view_sites', 'view_usage', 'view_billing', 'view_audit'],
        site: {
          site_id: 'site_agent_smoke',
          account_id: 'acct_agent_smoke',
          name: 'Agent Smoke Site',
          status: 'active',
          created_at: '2026-06-08T00:00:00Z',
        },
        sites: [
          {
            site_id: 'site_agent_smoke',
            site_name: 'Agent Smoke Site',
            account_id: 'acct_agent_smoke',
            status: 'active',
            created_at: '2026-06-08T00:00:00Z',
            plan_name: 'Smoke',
          },
        ],
        accounts: [],
      });
      return;
    }

    if (pathname === '/sites/site_agent_smoke/ai-insights/history') {
      await fulfillJson(route, {
        site_id: 'site_agent_smoke',
        items: [buildAIInsightHistoryItem()],
      });
      return;
    }

    if (pathname === '/sites/site_agent_smoke/ai-insights/analyze') {
      await fulfillJson(route, {
        site_id: 'site_agent_smoke',
        analysis: buildAIInsightAnalysis(),
        safety: {
          manual_trigger_required: true,
          prompt_saved: false,
          raw_payload_saved: false,
          wordpress_write_allowed: false,
          provider_visible: false,
          model_visible: false,
          token_usage_visible: false,
          cost_visible: false,
          cache_key_visible: false,
          customer_article_generation_allowed: false,
        },
      });
      return;
    }

    await route.continue();
  });
}

function buildAIInsightHistoryItem() {
  return {
    site_id: 'site_agent_smoke',
    scope: 'operations_analysis',
    status: 'attention',
    severity: 'warning',
    headline: 'Provider reliability needs review',
    operator_summary: 'Provider reliability requires operator review.',
    operator_next_step: 'Inspect failed provider calls before changing routing.',
    generated_at: '2026-06-08T00:00:00Z',
    fresh_until: '2026-06-08T00:30:00Z',
    is_stale: false,
    generation: {
      mode: 'llm',
      error_code: '',
      cache_status: 'miss',
      cache_hit: false,
      cache_generated_at: '2026-06-08T00:00:00Z',
      cache_expires_at: '2026-06-08T00:30:00Z',
    },
    ai_disclosure: {
      version: 'ai-generated-content-disclosure-v1',
      content_origin: 'ai_generated_internal_ops_summary',
      generated_by_ai: true,
      ai_assisted: true,
      visible_label_required: true,
      visible_label: 'AI generated',
      brand_label: 'Magick AI',
      visible_notice: 'Generated by Magick AI. Human review required before use.',
      review_status: 'needs_review',
      reviewed_at: '',
      source_generation_mode: 'llm',
    },
    agent_handoff: buildAgentBoundaryMetadata(),
    agent_registry_metadata: buildAgentBoundaryMetadata(),
  };
}

function buildAIInsightAnalysis() {
  return {
    summary_version: 'internal-ops-summarizer-v1',
    scope: 'operations_analysis',
    status: 'attention',
    severity: 'warning',
    headline: 'Provider reliability needs review',
    operator_summary: 'Provider reliability requires operator review.',
    operator_next_step: 'Inspect failed provider calls before changing routing.',
    safety_note: 'No WordPress write or routing adoption should happen from this advisory alone.',
    generated_at: '2026-06-08T00:00:00Z',
    generation: buildAIInsightHistoryItem().generation,
    ai_disclosure: buildAIInsightHistoryItem().ai_disclosure,
    agent_handoff: buildAgentBoundaryMetadata(),
    agent_registry_metadata: buildAgentBoundaryMetadata(),
  };
}

function buildAgentBoundaryMetadata() {
  return {
    agent_id: 'internal_ops_advisor_agent',
    agent_version: 'internal_ops_advisor_agent.v1',
    agent_role: 'operations_analysis',
    handoff_type: 'operator_recommendation',
    handoff_owner: 'cloud_internal_operator',
    requires_operator_review: true,
    direct_wordpress_write: false,
    execution_pattern: 'inline',
    storage_mode: 'result_only',
    allowed_actions: ['read_cloud_service_evidence'],
    stop_conditions: ['operator_action_required'],
    forbidden_actions: ['direct_wordpress_write', 'cloud_workflow_truth'],
    fail_closed_behavior: 'return_deterministic_advisory_summary',
  };
}

test('admin agent and workflow metadata panels render from Cloud registry responses', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const assertNoConsoleFailures = await expectNoConsoleFailures(page);

  await page.goto('/admin/dev-entry?redirect=%2Fadmin%2Fai-advisor');
  await expect(page).toHaveURL(/\/admin\/ai-advisor/);
  await expect(page.getByText('Agent handoff')).toBeVisible();
  await expect(page.getByText('internal_ops_advisor_agent', { exact: true })).toBeVisible();
  await expect(page.getByText('write blocked', { exact: true })).toBeVisible();
  await expect(page.getByText(/Cloud Workflow Truth/i)).toBeVisible();

  await page.goto('/admin/web-search');
  await expect(page.getByText('Workflow metadata')).toBeVisible();
  await expect(page.getByText('external_web_evidence_preflight')).toBeVisible();
  await expect(page.getByText('step_offload')).toBeVisible();
  await expect(page.getByText('wordpress_local')).toBeVisible();
  await expect(page.getByText('return_without_external_evidence')).toBeVisible();

  await page.goto('/admin/media-observability');
  await expect(page.getByText('media_derivative_artifact_generation')).toBeVisible();
  await expect(page.getByText('whole_run_offload')).toBeVisible();
  await expect(page.getByText('short_ttl_artifact')).toBeVisible();
  await expect(page.getByText('return_artifact_unavailable')).toBeVisible();

  assertNoConsoleFailures();
});

test('portal AI insights renders agent boundary from registry metadata', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await installPortalAIInsightMocks(page);
  const assertNoConsoleFailures = await expectNoConsoleFailures(page);

  await page.goto('/portal/ai-insights');
  await page.getByRole('button', { name: /Provider reliability needs review/i }).click();

  await expect(page.getByText('Agent boundary')).toBeVisible();
  await expect(page.getByText('internal_ops_advisor_agent', { exact: true })).toBeVisible();
  await expect(page.getByText('write blocked', { exact: true })).toBeVisible();
  await expect(page.getByText('review required', { exact: true })).toBeVisible();
  await expect(page.getByText('inline', { exact: true })).toBeVisible();
  await expect(page.getByText('result_only', { exact: true })).toBeVisible();
  await expect(page.getByText('return deterministic advisory summary')).toBeVisible();

  assertNoConsoleFailures();
});
