server {
    listen 100.86.14.81:18080;
    server_name _;

    root /var/lib/npcink-ai-cloud-m4-source-relay;
    autoindex off;
    access_log off;

    location / {
        limit_except GET HEAD {
            deny all;
        }

        disable_symlinks on;
    }
}
